apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: socat
  labels:
    app: socat
  namespace: default
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: socat
  minReplicas: 1
  maxReplicas: 10
  metrics:
    - type: Pods
      pods:
        metric:
          name: cpu_utilization
        target:
          type: AverageValue
          averageValue: 100m
  behavior:
    scaleDown:
      stabilizationWindowSeconds: 10
      policies:
      - type: Pods
        value: 5
        periodSeconds: 60
      selectPolicy: Max

